import type { SocialPost, Alert, SystemLog, MissingPerson, NetworkNode, InfectionData } from '@/types';

export const INITIAL_INFECTION_COUNT = 3_847_291;
export const INFECTION_RATE_PER_SECOND = 3.7;

export const socialPosts: SocialPost[] = [
  {
    id: '1',
    username: 'FEMA Emergency',
    handle: '@FEMA_OFFICIAL',
    content: 'MANDATORY EVACUATION ORDER — Zones 1-7 must evacuate immediately. Do NOT engage with infected individuals. Proceed to designated safe zones. This is NOT a drill.',
    timestamp: '2 min ago',
    likes: 48291,
    replies: 12847,
    isOfficial: true,
    verified: true,
    location: 'Washington D.C.',
  },
  {
    id: '2',
    username: 'Sarah K.',
    handle: '@sarahk_survivor',
    content: 'They\'re at the mall on 5th. We barricaded the roof. 23 of us. We have water for maybe 3 days. PLEASE if anyone can see this, the National Guard needs to know about Westfield Mall Sector 9. WE ARE ALIVE.',
    timestamp: '4 min ago',
    likes: 91847,
    replies: 47291,
    location: 'Los Angeles, CA',
  },
  {
    id: '3',
    username: '◈ D3LT4_F0RC3',
    handle: '@delta_ops_actual',
    content: 'COMMS CHECK: All Delta units rally at grid 44.7281° N, 93.4812° W. Radio silence until 0300. Command is aware. Stay frosty. //AUTHENTICATED//',
    timestamp: '7 min ago',
    likes: 2841,
    replies: 891,
    isMilitary: true,
    verified: true,
  },
  {
    id: '4',
    username: 'Mike Harrow',
    handle: '@mike_harrow_real',
    content: 'My neighbor just BIT my wife. She was fine this morning. I don\'t know what to do. I\'ve locked myself in the bathroom. The sounds outside are... oh god. Is this happening everywhere??',
    timestamp: '9 min ago',
    likes: 284729,
    replies: 98471,
    location: 'Chicago, IL',
  },
  {
    id: '5',
    username: 'CDC Director',
    handle: '@CDCDirector',
    content: 'UPDATE: The pathogen designated X-MRTZ-9 does NOT respond to known antivirals. Avoid all contact with infected. Transmission via fluid/bite confirmed. Airborne status — UNDER INVESTIGATION. Shelter in place.',
    timestamp: '11 min ago',
    likes: 1028471,
    replies: 294871,
    isOfficial: true,
    verified: true,
    location: 'Atlanta, GA',
  },
  {
    id: '6',
    username: '▓▒░USER_47291░▒▓',
    handle: '@xXxBrainz_NomxXx',
    content: 'hUngrY... sO HuNgRy... FiNd yOu... SmElL yOuR FEaR... ComInG fOr aLl oF yOu... DoNt LoCk tHe dOoRs... We WilL GeT iN... HHHHHHH',
    timestamp: '12 min ago',
    likes: 847291,
    replies: 184729,
    isInfected: true,
  },
  {
    id: '7',
    username: 'Dr. Aiden Frost',
    handle: '@dr_frost_bio',
    content: 'For those asking: the infected ARE reanimates. Neural activity is primitive — fight/hunger response only. Higher brain function is GONE. Do not attempt communication or negotiation. They cannot be helped. I\'m sorry.',
    timestamp: '15 min ago',
    likes: 749281,
    replies: 201847,
    verified: true,
    location: 'Johns Hopkins Medical',
  },
  {
    id: '8',
    username: 'Jessica T.',
    handle: '@jess_tries_to_live',
    content: 'Lost my dad last night. He turned. I had to... I can\'t type it. I\'m alone now. If you\'re in the Austin area and have a safe location, please respond. I have medical supplies. I just need people.',
    timestamp: '18 min ago',
    likes: 921847,
    replies: 129471,
    location: 'Austin, TX',
  },
  {
    id: '9',
    username: 'US Army Pacific',
    handle: '@USArmyPacific',
    content: 'OPERATION LAST LIGHT — Quarantine perimeters established at major metro areas. Use of lethal force AUTHORIZED against any entity breaching containment zones. Civilian advisory: remain indoors. Military will not open fire on uninfected civilians.',
    timestamp: '22 min ago',
    likes: 2847291,
    replies: 489271,
    isMilitary: true,
    verified: true,
    isOfficial: true,
  },
  {
    id: '10',
    username: '░░░░░░░░░░',
    handle: '@___________7',
    content: 'ThEy ArE eVeRyWhErE. YoU cAnNoT rUn. YoU cAnNoT hIdE. WE aRe yOuR nEiGhBoRs. WE aRe yOuR fAmIlY. WE aRe CoMiNg HoMe.',
    timestamp: '25 min ago',
    likes: 1847291,
    replies: 2847,
    isInfected: true,
  },
  {
    id: '11',
    username: 'Red Cross Emergency',
    handle: '@RedCross_Emergency',
    content: 'Safe refuge locations are OVERWHELMED. We are triaging. Priority: children under 12, medical personnel, and anyone with engineering or communications skills. Report to Zone Alpha points only. God help us all.',
    timestamp: '28 min ago',
    likes: 4921847,
    replies: 1847291,
    isOfficial: true,
    verified: true,
  },
  {
    id: '12',
    username: 'Hector V.',
    handle: '@hector_v_still_here',
    content: 'Day 4. Rooftop garden still growing. Got 14 people with me including 2 kids. We found a ham radio. Talking to a group in Phoenix. Trying to coordinate. This is NOT the end. WE ADAPT. WE SURVIVE.',
    timestamp: '31 min ago',
    likes: 2847291,
    replies: 847291,
    location: 'Denver, CO',
  },
];

export const emergencyAlerts: Alert[] = [
  {
    id: 'A1',
    level: 'critical',
    title: '⚠ BIOHAZARD LEVEL 5 — NATIONAL EMERGENCY',
    message: 'President has invoked Emergency Powers Act. MARTIAL LAW in effect for all metro areas. Curfew: 6PM-6AM. Violators may be subject to immediate containment.',
    timestamp: '00:03:14',
    source: 'PRESIDENTIAL EMERGENCY BROADCAST',
  },
  {
    id: 'A2',
    level: 'critical',
    title: '☣ INFECTION ZONE EXPANSION — EASTERN SEABOARD',
    message: 'Quarantine failure reported in Boston, Philadelphia, Baltimore. Containment breach imminent. All residents within 50 miles of affected zones must evacuate NORTH.',
    timestamp: '00:07:42',
    source: 'DEPT. OF HOMELAND SECURITY',
  },
  {
    id: 'A3',
    level: 'warning',
    title: '⚡ POWER GRID STATUS — CRITICAL',
    message: 'Eastern grid projected to fail within 72 hours. Fuel reserves at 12%. Nuclear plants entering emergency shutdown protocol. Backup generators have 96-hour capacity.',
    timestamp: '00:12:09',
    source: 'DEPARTMENT OF ENERGY',
  },
  {
    id: 'A4',
    level: 'warning',
    title: '🛡 MILITARY PERIMETER — SECURE ZONES',
    message: 'Sectors A through F confirmed secure. Delta Force maintaining outer perimeter. DO NOT approach military checkpoints without civilian ID. Shoot-on-sight orders in effect after dark.',
    timestamp: '00:19:33',
    source: 'JOINT CHIEFS OF STAFF',
  },
  {
    id: 'A5',
    level: 'info',
    title: '📡 SATELLITE UPLINK — DEGRADED',
    message: 'ISS crew reported safe. Orbital assets being repurposed for ground-based communication relay. Expect intermittent internet access over next 48 hours.',
    timestamp: '00:24:17',
    source: 'NASA EMERGENCY OPS',
  },
  {
    id: 'A6',
    level: 'critical',
    title: '☣ PATHOGEN UPDATE — MUTATION DETECTED',
    message: 'Lab analysis confirms X-MRTZ-9 has undergone rapid mutation. New strain designated X-MRTZ-9B shows increased transmission rate. Estimated doubling time: 6 hours.',
    timestamp: '00:31:55',
    source: 'CDC EMERGENCY RESPONSE',
  },
];

export const systemLogs: SystemLog[] = [
  { id: 'L1', timestamp: '04:17:33.291', level: 'CRITICAL', message: 'NODE FAILURE: backbone-east-01 unreachable. Rerouting via satellite uplink.', source: 'NET_CORE' },
  { id: 'L2', timestamp: '04:17:35.847', level: 'ERROR', message: 'Firewall breach detected. 847 unauthorized access attempts from unknown IPs.', source: 'SECURITY' },
  { id: 'L3', timestamp: '04:17:38.103', level: 'WARN', message: 'Power fluctuation detected. UPS engaged. Runtime: 47h 23m remaining.', source: 'POWER_MGMT' },
  { id: 'L4', timestamp: '04:17:41.509', level: 'CRITICAL', message: 'DNS root server alpha-7 has gone offline. Secondary routing active.', source: 'DNS_SYS' },
  { id: 'L5', timestamp: '04:17:44.712', level: 'INFO', message: 'Emergency broadcast relay ACTIVE. Uptime: 99.2%. Serving 47M connections.', source: 'BROADCAST' },
  { id: 'L6', timestamp: '04:17:47.891', level: 'ERROR', message: 'Database corruption detected in user_registry. Attempting repair...', source: 'DB_CORE' },
  { id: 'L7', timestamp: '04:17:50.234', level: 'WARN', message: 'Bandwidth saturation at 94%. Throttling non-emergency traffic.', source: 'TRAFFIC' },
  { id: 'L8', timestamp: '04:17:53.671', level: 'CRITICAL', message: 'Military override received. Re-prioritizing comm channels for OPERATION LAST LIGHT.', source: 'MIL_INTERFACE' },
  { id: 'L9', timestamp: '04:17:56.109', level: 'INFO', message: 'Infection counter sync: 3,847,291 confirmed. Data integrity: 87%.', source: 'BIOHAZ_TRACK' },
  { id: 'L10', timestamp: '04:17:59.445', level: 'ERROR', message: 'Social media rate limiter DISABLED. Emergency post flood in progress.', source: 'SOCIAL_SYS' },
  { id: 'L11', timestamp: '04:18:02.778', level: 'DEBUG', message: 'Sector 7G containment breach logged. Event ID: 0xDEAD7G01.', source: 'GEO_TRACK' },
  { id: 'L12', timestamp: '04:18:05.012', level: 'CRITICAL', message: 'ADMIN OVERRIDE: All encryption keys revoked. Emergency plain-text mode.', source: 'CRYPTO' },
  { id: 'L13', timestamp: '04:18:08.347', level: 'WARN', message: 'Anomalous traffic pattern detected. Possible coordinated DDoS by unknown actor.', source: 'SECURITY' },
  { id: 'L14', timestamp: '04:18:11.690', level: 'INFO', message: 'Civilian check-in portal: 2.1M successful. 890K failed (user terminated?).', source: 'CIVILIAN_SYS' },
  { id: 'L15', timestamp: '04:18:14.923', level: 'ERROR', message: 'Node backbone-west-03 reporting corrupted packets. Hardware failure suspected.', source: 'NET_CORE' },
  { id: 'L16', timestamp: '04:18:17.256', level: 'CRITICAL', message: '⚠ UNHANDLED EXCEPTION: outbreak_sim.exe has stopped responding. Restart? [Y/N]', source: 'SYSTEM' },
];

export const missingPersons: MissingPerson[] = [
  { id: 'M1', name: 'Emma Chen', age: 8, lastSeen: 'Maple Street Elementary, Chicago', description: 'Asian girl, black hair, pink backpack with unicorns. Wearing yellow raincoat.', contact: 'Father: David Chen — 312-555-0147', daysAgo: 2, status: 'missing' },
  { id: 'M2', name: 'Robert "Bobby" Vance', age: 34, lastSeen: 'Downtown Houston Medical Center', description: 'White male, 6\'1", brown hair, hospital scrubs (blue). May be injured.', contact: 'Wife: Amy Vance — 713-555-0293', daysAgo: 3, status: 'missing' },
  { id: 'M3', name: 'Maria Santos', age: 67, lastSeen: 'San Juan, Puerto Rico — Sector 4', description: 'Hispanic female, grey hair, uses cane. Speaks limited English. Takes heart medication.', contact: 'Daughter: Rosa Santos — 787-555-0184', daysAgo: 1, status: 'missing' },
  { id: 'M4', name: 'Tyler Brooks', age: 19, lastSeen: 'University of Michigan campus', description: 'Black male, 5\'10", dreadlocks, blue Michigan hoodie. Had laptop bag.', contact: 'Mom: Denise Brooks — 734-555-0671', daysAgo: 4, status: 'unknown' },
  { id: 'M5', name: 'Dr. Sarah Okafor', age: 41, lastSeen: 'CDC Lab Facility, Atlanta', description: 'Nigerian-American female, scientist. Last reported working on pathogen analysis. CRITICAL to recovery effort.', contact: 'CDC Emergency: 404-555-0019', daysAgo: 1, status: 'missing' },
  { id: 'M6', name: 'James & Lucy Harwood', age: 45, lastSeen: 'Harwood Farm, Rural Montana', description: 'Couple. James — white male, tall, beard. Lucy — white female, red hair. Had farm truck.', contact: 'Son: Caleb Harwood — 406-555-0332', daysAgo: 5, status: 'unknown' },
];

export const networkNodes: NetworkNode[] = [
  { id: 'N1', name: 'BACKBONE-EAST-01', status: 'offline', integrity: 0, region: 'Northeast US', lastPing: '47 min ago' },
  { id: 'N2', name: 'BACKBONE-WEST-03', status: 'degraded', integrity: 23, region: 'West Coast', lastPing: '2 min ago' },
  { id: 'N3', name: 'BACKBONE-CENTRAL', status: 'online', integrity: 78, region: 'Central US', lastPing: '12 sec ago' },
  { id: 'N4', name: 'SAT-RELAY-ALPHA', status: 'online', integrity: 91, region: 'Orbital', lastPing: '8 sec ago' },
  { id: 'N5', name: 'MIL-NET-NODE-7', status: 'online', integrity: 99, region: 'Classified', lastPing: '1 sec ago' },
  { id: 'N6', name: 'EU-BRIDGE-01', status: 'compromised', integrity: 12, region: 'Europe', lastPing: '1 hr ago' },
  { id: 'N7', name: 'ASIA-PAC-HUB', status: 'degraded', integrity: 45, region: 'Asia Pacific', lastPing: '8 min ago' },
  { id: 'N8', name: 'EMERGENCY-RELAY', status: 'online', integrity: 88, region: 'National', lastPing: '3 sec ago' },
];

export const infectionData: InfectionData[] = [
  { region: 'Northeast US', confirmed: 1284920, suspected: 2891047, critical: 482917, trend: 'rising' },
  { region: 'Southeast US', confirmed: 892147, suspected: 1847291, critical: 391847, trend: 'rising' },
  { region: 'Midwest US', confirmed: 491847, suspected: 1029471, critical: 201847, trend: 'rising' },
  { region: 'West Coast', confirmed: 712841, suspected: 1492817, critical: 284719, trend: 'rising' },
  { region: 'Europe', confirmed: 2847291, suspected: 5819471, critical: 1284910, trend: 'rising' },
  { region: 'Asia Pacific', confirmed: 1492817, suspected: 3819471, critical: 891847, trend: 'rising' },
  { region: 'Australia', confirmed: 284719, suspected: 591847, critical: 91847, trend: 'stable' },
];
